apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-db'
  labels:
    katenary.io/component: db
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 68f605431a7d36e10137c004d91785087946b59b
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: db
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: db
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: db
          image: '{{ .Values.db.repository.image }}{{ if ne .Values.db.repository.tag "" }}:{{ .Values.db.repository.tag }}{{ end }}'
          ports:
            - name: db
              containerPort: 5432
          envFrom:
            - configMapRef:
                name: '{{ .Release.Name }}-db'
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres
            periodSeconds: 5
            initialDelaySeconds: 0
            successThreshold: 1
            failureThreshold: 5
      volumes:
        - name: db
          {{- if  .Values.db.persistence.db.enabled }}
          persistentVolumeClaim:
            claimName: '{{ .Release.Name }}-db'
          {{ else }}
          emptyDir: {}
          {{- end }}

